### ISSUE TITLE
STT: Desenvolupament del tràmit d'instància genèrica

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/sistra2#134]
Es sol·licita la implementació del tràmit d'instància genèrica sobre SISTRA2, amb els següents requeriments:
- El tràmit implementarà la tramitació d'un procediment o servei administratiu ROLSAC amb codi SIA.
- El formulari ha de permetre seleccionar la UA de tramitació des d'un selector a nivell de Conselleria (domini remot contra DIR3CAIB i si no es possible via domini de BD-DataSource).
- El tràmit he de requerir autenticació per certificat i requerir signatura de la sol·licitud. 
- La informació que es passarà a Registre serà el codiSIA del proced./servei i el codi DIR3 que hagi emplenat el ciutadà en el formulari. En aquest sentit, es sol·licita afegir la funcionalitat necessària a nivell de script per fixar de manera dinàmica l'òrgan de destí del tràmit.

**Comment by jsastre-dgtic** [comment]
Detectats errors de plataforma:
1.- Passa Annexar
![image](https://user-images.githubusercontent.com/18436867/57280747-b467db80-70a9-11e9-8d57-fe3dbe524f3d.png)

2.- Per aconseguir focus al camp sol·licito necessitam fer 3 clics.
De la mateixa manera, necessitam fer 3 clics al botó Finalitza per tal de que sigui operatiu i faci l'acció de finalitzar.
Entenc que aquest és un comportament horitzontal de la plataforma, que no és desitjable. 
Té solució?
![image](https://user-images.githubusercontent.com/18436867/57280854-fb55d100-70a9-11e9-828f-072774703736.png)

![image](https://user-images.githubusercontent.com/18436867/57280868-03157580-70aa-11e9-9e8f-7234c7cf4d0c.png)


3.- A més de l'error d'importació hi ha un error que exigeix emplenat el camp de representant, quan no hauria de ser obligatori:

Caused by: es.caib.sistramit.core.api.exception.ErrorScriptException: El trámite admite representacion y no se ha especificado representado en el script at es.caib.sistramit.core.service.component.flujo.pasos.registrar.ControladorPasoRegistrarHelper.ejecutarScriptRepresentado(ControladorPasoRegistrarHelper.java:200)

**Comment by rsanz-indra** [comment]
Las incidencias 1 y 3 se han solucionado.
La incidencia 2 es de difícil resolución debido a los eventos javascript, se intentará mejorar en futuras versiones.
Además se han desarrollado otras funcionalidades detectadas durante las pruebas funcionales del trámite.
Queda pendiente de finalizar el envío de correos tras registrar.
